import 'dart:convert';

/// Represents a scheduled workout within a program.
class ProgramWorkout {
  final String workoutId;
  final DateTime scheduledDate;

  const ProgramWorkout({
    required this.workoutId,
    required this.scheduledDate,
  });

  factory ProgramWorkout.fromJson(Map<String, dynamic> json) => ProgramWorkout(
        workoutId: json['workoutId'] as String,
        scheduledDate: DateTime.parse(json['scheduledDate'] as String),
      );

  Map<String, dynamic> toJson() => {
        'workoutId': workoutId,
        'scheduledDate': scheduledDate.toIso8601String(),
      };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgramWorkout &&
          other.workoutId == workoutId &&
          other.scheduledDate == scheduledDate;

  @override
  int get hashCode => workoutId.hashCode ^ scheduledDate.hashCode;
}

/// A named program consisting of a schedule of workouts.
class Program {
  /// Unique identifier for the program
  final String id;

  /// Display name of the program
  final String name;

  /// List of scheduled workouts in this program
  final List<ProgramWorkout> schedule;

  /// Whether to send a daily reminder for this program's scheduled workouts.
  final bool notificationEnabled;

  /// Reminder time as minutes since midnight (0-1439), or null if not set.
  /// Used only when [notificationEnabled] is true.
  final int? notificationTimeMinutes;

  /// Whether this program was generated by AI.
  final bool isAiGenerated;

  /// JSON-encoded context used for AI generation (user inputs, scorecard, etc.).
  final String? generationContext;

  /// Which week is the deload week (e.g. 4 means week 4).
  final int? deloadWeek;

  /// AI-generated notes about weekly progression strategy.
  final String? weeklyProgressionNotes;

  /// Coach voice intro (2–3 sentences) for programme reveal card.
  final String? coachIntro;

  /// Full coach rationale (4–6 paragraphs) for "About your programme" screen.
  final String? coachRationale;

  /// Shorter ear-first script for Type C TTS only; not shown on About. From LLM as coachRationaleSpoken.
  final String? coachRationaleSpoken;

  /// JSON: list of { workoutId, briefDescription, exercises: [{ exerciseId, coachNote }] } for About screen breakdowns.
  final String? workoutBreakdowns;

  /// Firebase Storage path for generated programme description audio (Type C), if uploaded.
  final String? programmeDescriptionAudioRemotePath;

  /// Constructs a Program. `schedule` may be empty.
  const Program({
    required this.id,
    required this.name,
    this.schedule = const [],
    this.notificationEnabled = false,
    this.notificationTimeMinutes,
    this.isAiGenerated = false,
    this.generationContext,
    this.deloadWeek,
    this.weeklyProgressionNotes,
    this.coachIntro,
    this.coachRationale,
    this.coachRationaleSpoken,
    this.workoutBreakdowns,
    this.programmeDescriptionAudioRemotePath,
  });

  /// Create a Program from a JSON map.
  factory Program.fromJson(Map<String, dynamic> json) {
    final schedule = (json['schedule'] as List<dynamic>?)
            ?.map((e) => ProgramWorkout.fromJson(e as Map<String, dynamic>))
            .toList() ??
        <ProgramWorkout>[];
    return Program(
      id: json['id'] as String,
      name: json['name'] as String,
      schedule: schedule,
      notificationEnabled: json['notificationEnabled'] as bool? ?? false,
      notificationTimeMinutes: json['notificationTimeMinutes'] as int?,
      isAiGenerated: json['isAiGenerated'] as bool? ?? false,
      generationContext: json['generationContext'] as String?,
      deloadWeek: json['deloadWeek'] as int?,
      weeklyProgressionNotes: json['weeklyProgressionNotes'] as String?,
      coachIntro: json['coachIntro'] as String?,
      coachRationale: json['coachRationale'] as String?,
      coachRationaleSpoken: json['coachRationaleSpoken'] as String?,
      workoutBreakdowns: json['workoutBreakdowns'] as String?,
      programmeDescriptionAudioRemotePath:
          json['programmeDescriptionAudioRemotePath'] as String?,
    );
  }

  /// Copy with updated [workoutBreakdowns] (e.g. after generating spoken intros).
  Program copyWith({
    String? workoutBreakdowns,
    String? programmeDescriptionAudioRemotePath,
    String? coachRationaleSpoken,
  }) =>
      Program(
        id: id,
        name: name,
        schedule: schedule,
        notificationEnabled: notificationEnabled,
        notificationTimeMinutes: notificationTimeMinutes,
        isAiGenerated: isAiGenerated,
        generationContext: generationContext,
        deloadWeek: deloadWeek,
        weeklyProgressionNotes: weeklyProgressionNotes,
        coachIntro: coachIntro,
        coachRationale: coachRationale,
        coachRationaleSpoken: coachRationaleSpoken ?? this.coachRationaleSpoken,
        workoutBreakdowns: workoutBreakdowns ?? this.workoutBreakdowns,
        programmeDescriptionAudioRemotePath: programmeDescriptionAudioRemotePath ??
            this.programmeDescriptionAudioRemotePath,
      );

  /// Convert this Program into a JSON-serializable map.
  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'schedule': schedule.map((e) => e.toJson()).toList(),
        'notificationEnabled': notificationEnabled,
        if (notificationTimeMinutes != null) 'notificationTimeMinutes': notificationTimeMinutes,
        'isAiGenerated': isAiGenerated,
        if (generationContext != null) 'generationContext': generationContext,
        if (deloadWeek != null) 'deloadWeek': deloadWeek,
        if (weeklyProgressionNotes != null) 'weeklyProgressionNotes': weeklyProgressionNotes,
        if (coachIntro != null) 'coachIntro': coachIntro,
        if (coachRationale != null) 'coachRationale': coachRationale,
        if (coachRationaleSpoken != null) 'coachRationaleSpoken': coachRationaleSpoken,
        if (workoutBreakdowns != null) 'workoutBreakdowns': workoutBreakdowns,
        if (programmeDescriptionAudioRemotePath != null)
          'programmeDescriptionAudioRemotePath': programmeDescriptionAudioRemotePath,
      };

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! Program) return false;
    return other.id == id &&
        other.name == name &&
        _listEquals(other.schedule, schedule) &&
        other.notificationEnabled == notificationEnabled &&
        other.notificationTimeMinutes == notificationTimeMinutes &&
        other.isAiGenerated == isAiGenerated &&
        other.generationContext == generationContext &&
        other.deloadWeek == deloadWeek &&
        other.weeklyProgressionNotes == weeklyProgressionNotes &&
        other.coachIntro == coachIntro &&
        other.coachRationale == coachRationale &&
        other.coachRationaleSpoken == coachRationaleSpoken &&
        other.workoutBreakdowns == workoutBreakdowns &&
        other.programmeDescriptionAudioRemotePath == programmeDescriptionAudioRemotePath;
  }

  @override
  int get hashCode => Object.hash(
        id,
        name,
        _listHashCode(schedule),
        notificationEnabled,
        notificationTimeMinutes,
        isAiGenerated,
        generationContext,
        deloadWeek,
        weeklyProgressionNotes,
        coachIntro,
        coachRationale,
        coachRationaleSpoken,
        workoutBreakdowns,
        programmeDescriptionAudioRemotePath,
      );

  @override
  String toString() => jsonEncode(toJson());

  // Helper: list equality
  static bool _listEquals(List a, List b) {
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (a[i] != b[i]) return false;
    }
    return true;
  }

  // Helper: combine list items into hash
  static int _listHashCode(List items) {
    return items.fold(0, (prev, e) => prev ^ e.hashCode);
  }
}